services:
  api:
    restart: unless-stopped
    container_name: vokrub-api
    build:
      context: .
      args:
        - BUILD_ENV=${BUILD_ENV:-production}
    env_file:
      - ${ENV_FILE}
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
